<a href="https://colab.research.google.com/github/Piyush-41/Breast-Cancer-Prediction-using-Neural-Network/blob/main/Breast_Cancer_Prediction_using_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing dependencies
import torch
import torch.nn as nn
import torch.optim as optim #for optimizer (adam,sgd)
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [ ]:
#Device Configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)



cuda


In [ ]:
#data collection and pre processing
data = load_breast_cancer()
X = data.data
Y = data.target

In [ ]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [ ]:
#split the data set into traning and test
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
print(X.shape)


(569, 30)


In [ ]:
print(X_train.shape)

(455, 30)


In [ ]:
print(X_test.shape)


(114, 30)


In [ ]:
#data standardiastion
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
type(X_train)

numpy.ndarray

In [ ]:
#we cant use num py in torch so we have to convert it to PyTorch tensars

X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
Y_train = torch.tensor(Y_train, dtype=torch.float32).to(device)
X_test = torch.tensor(X_test, dtype=torch.float32).to(device)
Y_test = torch.tensor(Y_test, dtype=torch.float32).to(device)

In [ ]:
#neural network architecture in PyTorch

class NeuralNet(nn.Module):

  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, num_classes) # Changed output_size to num_classes, assuming num_classes is the intended output size
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
#define hyper parameters
input_size = X_train.shape[1]#30
hidden_size = 64
output_size = 1
learning_rate=0.001
num_epochs = 100


In [ ]:
#initialize the nn and move ot gpu
model = NeuralNet(input_size, hidden_size, output_size).to(device)


In [ ]:
#define loss and the optimizers
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
#traning the nn
for epoch in range(num_epochs):
  model.train()
  optimizer.zero_grad()
  outputs = model(X_train)
  loss = criterion(outputs, Y_train.view(-1,1))
  loss.backward()
  optimizer.step()

  #calculation accuracy
  with torch.no_grad():
    outputs = model(X_test)
    predicted = outputs.round()
    # Compare with Y_test, not Y_train, and use .float() for casting
    correct = (predicted == Y_test.view(-1,1)).float().sum()
    accuracy = correct / Y_test.size(0)

  # Move print statement inside the loop
  if (epoch+1) % 10 == 0:
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {accuracy.item()*100:.2f}%")

Epoch [10/100], Loss: 0.5299, Accuracy: 96.49%
Epoch [20/100], Loss: 0.4107, Accuracy: 97.37%
Epoch [30/100], Loss: 0.3224, Accuracy: 96.49%
Epoch [40/100], Loss: 0.2582, Accuracy: 96.49%
Epoch [50/100], Loss: 0.2127, Accuracy: 96.49%
Epoch [60/100], Loss: 0.1804, Accuracy: 97.37%
Epoch [70/100], Loss: 0.1570, Accuracy: 97.37%
Epoch [80/100], Loss: 0.1394, Accuracy: 98.25%
Epoch [90/100], Loss: 0.1257, Accuracy: 98.25%
Epoch [100/100], Loss: 0.1148, Accuracy: 98.25%


In [ ]:
#model evaluation
model.eval()
with torch.no_grad():
  outputs = model(X_test)
  predicted = outputs.round()
  correct = (predicted == Y_test.view(-1,1)).float().sum()
  accuracy = correct / Y_test.size(0)
  print(f"accuracy on traning data:{accuracy.item()*100:.2f}%")

accuracy on traning data:98.25%


### Enter Your Data for Prediction

To get a prediction, please enter 30 numerical values corresponding to the features of a new sample. These values should be provided as a Python list in the cell below.

**Important:** Ensure you provide exactly 30 numerical values. The model expects input in this format.

In [ ]:
# --- USER INPUT SECTION ---
# Modify the list below with your 30 feature values.
# Example values are from a 'not cancerous' sample for demonstration.
user_data_for_prediction = [
20.13, 28.25, 131.20, 1261.0, 0.09780, 0.10340, 0.14400, 0.09791, 0.1752, 0.05533, 0.7655, 2.463, 5.203, 99.04, 0.005769, 0.02423, 0.03950, 0.01678, 0.01898, 0.002498, 23.690, 38.25, 155.00, 1731.0, 0.11660, 0.19220, 0.3215, 0.1628, 0.2572, 0.06637
]

# --- DO NOT MODIFY BELOW THIS LINE ---
if len(user_data_for_prediction) != input_size:
    print(f"Error: You must provide exactly {input_size} features. You provided {len(user_data_for_prediction)}.")
else:
    predicted_result = predict_new_sample(user_data_for_prediction, model, scaler, device)

    print(f"\nInput Data: {user_data_for_prediction}")
    if predicted_result == 0.0:
         print("Prediction: Cancerous M ")
    else:
         print("Prediction: Not Cancerous B")


Input Data: [20.13, 28.25, 131.2, 1261.0, 0.0978, 0.1034, 0.144, 0.09791, 0.1752, 0.05533, 0.7655, 2.463, 5.203, 99.04, 0.005769, 0.02423, 0.0395, 0.01678, 0.01898, 0.002498, 23.69, 38.25, 155.0, 1731.0, 0.1166, 0.1922, 0.3215, 0.1628, 0.2572, 0.06637]
Prediction: Cancerous M 
